In [1]:
import pandas as pd
import numpy as np

In [11]:
arr = np.array([
    [500, 200],
    [200, 300],
    [50251, 52315],
    [273, 37517]
], dtype = np.uint16)

print(f"shape: {arr.shape}\nsize: {arr.size}\nndim: {arr.ndim}")

shape: (4, 2)
size: 8
ndim: 2


In [19]:
arr = np.arange(100, 200, 10, dtype=np.int64).reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [25]:
#prnt only third row
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray[:, 2])

[33 66 99]


In [31]:
# Return array of odd rows and even columns from below numpy array
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray.shape)

wtf = sampleArray[::2, 1::2]
print(wtf)

(5, 4)
[[ 6 12]
 [30 36]
 [54 60]]


In [36]:
# Create a result array by adding the following two NumPy arrays. 
# Next, modify the result array by calculating the square of each element
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

new_arr = (arrayOne + arrayTwo) **2
print(new_arr)


[[ 400 1521 1089]
 [ 625  625  784]]


In [55]:
# (8,3) np arr to 4 sub np arr
sample_arr = np.arange(10, 34).reshape(8, 3)
sub_arr = np.array(np.split(sample_arr, 4))
print(sample_arr)
print(sub_arr)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]

 [[22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]]]


In [57]:
# sorting
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

sortArrayByRow = sampleArray[:,sampleArray[1,:].argsort()]
print("Sorting Original array by secoond row")
print(sortArrayByRow)

print("Sorting Original array by secoond column")
sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]
print(sortArrayByColumn)

Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [ ]:
### print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

minOfAxisOne = np.amin(sampleArray, axis=1) 
print("Printing amin Of Axis 1")
print(minOfAxisOne)

maxOfAxisOne = np.amax(sampleArray, 0) 
print("Printing amax Of Axis 0")
print(maxOfAxisOne)

In [68]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])
# axis 0 is looking down / vertical
# axis 1 is looking horizontal / left-right
print(np.max(data, axis=1))

[ 3  6  9 12]


In [87]:
arr = np.arange(10, 22, 1).reshape(4,3)
arr2 = np.array([[1,5,7],
                [9,10,12],
                [3,4,22],
                [7,9,4]])
print(np.amax(arr2, axis=0))

print(np.mean(arr2, axis=1))

[ 9 10 22]
[ 4.33333333 10.33333333  9.66666667  6.66666667]
